### ISSUE TITLE
COSESign1 verify throws "Failed to verify the signature: Invalid encoding for signature"

### ISSUE THREAD

**Issue by mikekelly** [authlete/cbor#8]
If you try to verify a COSESign1 message, it throws `com.authlete.cose.COSEException: Failed to verify the signature: Invalid encoding for signature`. Steps to reproduce:

```
        val anyPubKey = // generate a valid ECPublicKey
        val sign1Hex = "D28441A0A201260442313154546869732069732074686520636F6E74656E742E584087DB0D2E5571843B78AC33ECB2830DF7B6E0A4D5B7376DE336B23C591C90C425317E56127FBE04370097CE347087B233BF722B64072BEB4486BDA4031D27244F"
        val sign1Bytes = sign1Hex.hexToByteArray()
        val sign1TaggedItem = CBORDecoder(sign1Bytes).next() as CBORTaggedItem
        val sign1 = sign1TaggedItem.tagContent as COSESign1

        COSEVerifier(anyPubKey).verify(sign1)
```

The signature in question here definitely isn't invalid because it's taken from the official example messages in the COSE repo, and validate properly with other COSE libraries:

https://github.com/cose-wg/Examples/blob/master/sign1-tests/sign-pass-01.json

**Comment by mikekelly** [comment]
Stacktrace:

```
com.authlete.cose.COSEException: Failed to verify the signature: Invalid encoding for signature
	at app//com.authlete.cose.ECDSA.verifySignature(ECDSA.java:599)
	at app//com.authlete.cose.ECDSA.verify(ECDSA.java:414)
	at app//com.authlete.cose.COSEVerifier.verify(COSEVerifier.java:385)
	at app//com.authlete.cose.COSEVerifier.verify(COSEVerifier.java:268)
	at app//com.authlete.cose.COSEVerifier.verify(COSEVerifier.java:232)
```

**Comment by mikekelly** [comment]
nevermind, this appears to be a bug in my fork apologies
